spring.application.name=productsorders

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/productsorders
spring.datasource.username=usr
spring.datasource.password=pwd

# Liquibase
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml