spring.application.name=booksauthors

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/usersorders
spring.datasource.username=usr
spring.datasource.password=pwd

# Liquibase
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
